{
 "title": "WAN",
 "time": { "from": "2020-07-07T22:17:49.215Z", "to": "2020-07-07T22:45:20.979Z" },
 "templating": {
  "list": [
   {
    "name": "Import",
    "query": "SHOW TAG VALUES WITH KEY = import_id"
   },
   {
    "name": "WAN_Source",
    "query": "SHOW TAG VALUES WITH KEY = benchmark"
   },
   {
    "name": "WAN_Target",
    "query": "SHOW TAG VALUES WITH KEY = benchmark"
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.partitionCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Completed Migrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.totalCompletedMigrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Cost",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.ownedEntryMemoryCost",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.partitionCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Completed Migrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.totalCompletedMigrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Cost",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.ownedEntryMemoryCost",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Sync count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.syncCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Update Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.updateCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Remove Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.removeCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Dropped count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.droppedCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Outbound Q",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.outboundQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Pub Event Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.totalPublishedEventCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Pub Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.totalPublishLatency",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  }
 ]
}