{
 "title": "WAN",
 "time": { "from": "2020-07-07T15:01:01.232Z", "to": "2020-07-07T23:11:57.684Z" },
 "templating": {
  "list": [
   {
    "name": "Import",
    "query": "SHOW TAG VALUES WITH KEY = import_id"
   },
   {
    "name": "WAN_Source",
    "query": "SHOW TAG VALUES WITH KEY = benchmark"
   },
   {
    "name": "WAN_Target",
    "query": "SHOW TAG VALUES WITH KEY = benchmark"
   }
  ]
 },
 "panels": [
  { "title": "Target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.partitionCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Entries",
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Updates",
     "measurement": "map.setCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Inserts",
     "measurement": "map.putCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Deletes",
     "measurement": "map.removeCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "cluster.size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "client.endpoint.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Completed Migrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.totalCompletedMigrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Cost",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.ownedEntryMemoryCost",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "OS CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "cpu.usr",
     "query": "SELECT abs(\"pct\" -100) FROM \"autogen\".\"cpu.idl\" WHERE (\"benchmark\" =~ /^$WAN_Target$/ AND \"import_id\" =~ /^$Import$/) AND $timeFilter GROUP BY \"node\"",
     "select": [
      [
       { "params": [ "pct" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "OS Free Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "mem.free",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "memory.usedHeap",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Merkle Tree Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.merkleTreesCost",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net In Q",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.inputThread.taskQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net out Q",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.outputThread.taskQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Target Map Entry Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map put latency (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "map.putLatencyAvg",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Ack Delay Total Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "wan.ackDelayTotalCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "import_id", "operator": "=~", "value": "/^$Import$/" },
      { "condition": "AND", "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" }
     ]
    }
   ]
  },
  {
   "title": "Net rcv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 29 },
   "yaxes": [
    { "format": "Gbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "net.rcv",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ " * 0.000000008" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net snd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "Gbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "net.snd",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ " * 0.000000008" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.connection.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "import_id", "operator": "=~", "value": "/^$Import$/" },
      { "condition": "AND", "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" }
     ]
    }
   ]
  },
  { "title": "Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.partitionCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Entries",
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Updates",
     "measurement": "map.setCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Inserts",
     "measurement": "map.putCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    },
    {
     "alias": "Deletes",
     "measurement": "map.removeCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "cluster.size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "client.endpoint.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Completed Migrations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "partitions.totalCompletedMigrations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map Entry Cost",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.ownedEntryMemoryCost",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "OS CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "cpu.usr",
     "query": "SELECT abs(\"pct\" -100) FROM \"autogen\".\"cpu.idl\" WHERE (\"benchmark\" =~ /^$WAN_Source$/ AND \"import_id\" =~ /^$Import$/) AND $timeFilter GROUP BY \"node\"",
     "select": [
      [
       { "params": [ "pct" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Target$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "OS Free Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "-",
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "mem.free",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "memory.usedHeap",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Merkle Tree Cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "map.merkleTreesCost",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net In Q",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.inputThread.taskQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net out Q",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.outputThread.taskQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Source Map Entry Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "map.entryCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Map put latency (avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "map.totalMaxPutLatency",
     "select": [
      [
       { "params": [ "ms" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Connection counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "endpoint" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "tcp.connection.count",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "import_id", "operator": "=~", "value": "/^$Import$/" },
      { "condition": "AND", "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" }
     ]
    }
   ]
  },
  {
   "title": "Net rcv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 75 },
   "yaxes": [
    { "format": "Gbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "net.rcv",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ " * 0.000000008" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "Net snd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 75 },
   "yaxes": [
    { "format": "Gbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "net.snd",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ " * 0.000000008" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Sync count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.syncCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Update Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.updateCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Remove Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.removeCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Dropped count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.droppedCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Outbound Q",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.outboundQueueSize",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Pub Event Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.totalPublishedEventCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Pub Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "node" ], "type": "tag" }
     ],
     "measurement": "wan.publishLatencyAvg",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "benchmark", "operator": "=~", "value": "/^$WAN_Source$/" },
      { "condition": "AND", "key": "import_id", "operator": "=~", "value": "/^$Import$/" }
     ]
    }
   ]
  }
 ]
}